image: docker:20.10.8

stages:
  - build
  - release

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

services:
  - docker:20.10.8-dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

build-optimised:
  stage: build
  script:
    - docker build --pull -t "$CONTAINER_TEST_IMAGE-optimised"
    - docker push "$CONTAINER_TEST_IMAGE-optimised"

release:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
    - docker pull "$CONTAINER_TEST_IMAGE-optimised"
    - docker tag "$CONTAINER_TEST_IMAGE-optimised" "$CONTAINER_RELEASE_IMAGE-optimised"
    - docker push "$CONTAINER_RELEASE_IMAGE-optimised"